### ISSUE TITLE
Not all councils called councils

### ISSUE THREAD

**Issue by DsposalTom** [JackGilmore/OpenWasteMap#2]
Hey @JackGilmore 

I think in the OSM query we are just looking for "council" however some councils (like Greater Manchester Combined Authority) don't have council in their name so they are being missed.

This is and example https://www.openstreetmap.org/way/288125858

Maybe adding AND "Authority" might help until we get a better solution.

Great work on everything

**Comment by JackGilmore** [comment]
Thanks @DsposalTom. I'll look into this.
![image](https://user-images.githubusercontent.com/46202639/112289159-f55d3f00-8c85-11eb-910e-9e3fb97247d4.png)

It's probably a good idea to change the wording on the map to "authority" as well rather than council. I'm also looking for a county council polygon dataset further to what you pointed out on Slack the other day there regarding county vs district

**Comment by DsposalTom** [comment]
@JackGilmore - I'll have a look at the full data set to find the "neatest" option when considering County/Authority/Shire/Borough etc.

Need to go a level up really and just match on "Local Authority" = TRUE.

I wish that existed! But oh well

**Comment by JackGilmore** [comment]
@DsposalTom - This is a link to the current data source for the boundary polygons: https://geoportal.statistics.gov.uk/datasets/1d78d47c87df4212b79fe2323aae8e08_0?geometry=-44.248%2C51.101%2C39.380%2C59.782

It's currently filtering on the `lad19cd` property which matches to the `codes.admin_district` value from the postcodes.io API. 

I'd also like to download the polygons from the above dataset and host them locally within the site as GeoJSON files rather than making an external API on each search which could take time vs. caching and serving locally

**Comment by DsposalTom** [comment]
I'll have a chat with Georgios at our end as he has some experience of umbraco/lucene/examine/spatial stuff that might be useful

**Comment by JackGilmore** [comment]
I might be able to just process the data in QGIS but I'm keen to hear if you guys have any better ideas

**Comment by JackGilmore** [comment]
@DsposalTom Would this be the correct dataset? https://geoportal.statistics.gov.uk/datasets/counties-and-unitary-authorities-december-2019-boundaries-uk-bfc?geometry=-39.920%2C49.530%2C43.708%2C58.520

**Comment by DsposalTom** [comment]
@JackGilmore I think that is the one,

A technical officer at a LA gave me these links too that might be useful

https://geoportal.statistics.gov.uk/datasets/local-authority-districts-april-2019-names-and-codes-in-the-united-kingdom
https://geoportal.statistics.gov.uk/datasets/local-authority-districts-december-2019-names-and-codes-in-the-united-kingdom
https://www.ons.gov.uk/methodology/geography/geographicalproducts/namescodesandlookups/namesandcodeslistings

I might see if I can reach out to some knowledgeable people

**Comment by DsposalTom** [comment]
@JackGilmore I think this is the list of LA authority terms


Council
Shire
City Region
Comhairle nan Eilean Siar
Authority
Borough

**Comment by JackGilmore** [comment]
Thanks @DsposalTom. I managed to sort out the LAs for Scotland, Northern Ireland and Wales last night and convert them to geoJSON: https://github.com/JackGilmore/OpenWasteMap/tree/LA-polygons/OpenWasteMapUK/OpenWasteMapUK/wwwroot/assets/geo/local-authorities

**Comment by JackGilmore** [comment]
This is resolved as of c0f06cf9f9fd5f636de5f46c8e682e009124f875. Closing...

**Comment by DsposalTom** [comment]
@JackGilmore can we look at this item next please?  What can I do to help

**Comment by JackGilmore** [comment]
Hey @DsposalTom. No worries, we're in a good place to look at this now that caching is in place. There's two immediate potential options I can see here:

1. Expand the owner tag criteria to check for features that contain any LA related terms e.g.

Council
Shire
City Region
Comhairle nan Eilean Siar
Authority
Borough

This might not be the most reliable method and seems a bit messy IMO?

2. Use the ownership tag and look for ownership="municipal". This would be assuming that all HWRCs provided by LAs (whether privately operated or not) would have a municipal ownership. Again, not sure how reliable this assumption is. You may know about this better than I do?

I think it would be a good idea to construct some overpass queries for these two options (and any others we can think of) and compare the datasets to see what sort of results we're getting back. 

Think this is also going to be a good idea to work on updating the overpass query to work based off of country boundaries rather than defining a bounding box as I've specified in issue #6. At the moment the bounding box clips France and ROI so we risk picking up countries there.

**Comment by DsposalTom** [comment]
I think using the ownership as "municipal" is the better of the two ideas as it's not a fuzzy match.

Great idea

**Comment by JackGilmore** [comment]
New query: https://overpass-turbo.eu/s/1anW

**Comment by JackGilmore** [comment]
Updated query as geocodeArea function is an Overpass Turbo only feature https://overpass-turbo.eu/s/1aob

**Comment by DsposalTom** [comment]
Wonderful!!! I’ll look at those!!

**Comment by JackGilmore** [comment]
Did some analysis this evening comparing the datasets from the old query vs. the new query. The good news is that we're now picking up HWRCs from local authorities not containing "council" (or typo'd) like:
| name                                               | owner                                     |
| -------------------------------------------------- | ----------------------------------------- |
| Villiers Road Household Reuse and Recycling Centre | The Royal Borough of Kingston upon Thames |
| Mayton Wood Recycling Centre Plus                  | NULL                                      |
| Chester Road Recycling Centre                      | Greater Manchester Combined Authority     |
| Hove Recycling Centre                              | Brighton & Hove City Counci               |

The bad news is we're going to drop 34 HWRCs that don't have the "owner" tag set to "municipal":
| name                                                    | la                                      |
| ------------------------------------------------------- | --------------------------------------- |
| Torbay Waste Transfer and Recycling Centre              | Torbay Council                          |
| Totnes Recycling Centre                                 | Devon County Council                    |
| Brunel Road Recycling Centre                            | Devon County Council                    |
| Pershore (Hill and Moor) Household Recycling Centre     | Worcestershire County Council           |
| Shaftesbury Household Recycling Centre                  | Dorset Council                          |
| Bromley Farm                                            | Kirklees Metropolitan Council           |
| Weaving Lane Recycling Centre                           | Kirklees Metropolitan Council           |
| Milner's Road Waste Sorting Site                        | Leeds City Council                      |
| North Tyneside Household Waste Recycling Centre         | North Tyneside Council                  |
| Antrim Civic Amenity Centre                             | Antrim and Newtownabbey Borough Council |
| Glossop household waste recycling centre                | Derbyshire County Council               |
| Newport Pagnell Household Waste Recyling Centre         | Milton Keynes Council                   |
| Aldershot Household Waste Recycling Centre              | Hampshire County Council                |
| New Bradwell Household Waste Recycling Centre           | Milton Keynes Council                   |
| Haverhill Recycling Centre                              | Suffolk County Council                  |
| Northampton Sixfields Household Waste Recycling Centre  | West Northamptonshire Council           |
| Brechin Recycling Centre                                | Angus Council                           |
| Bent Ley Road Recycling Centre                          | Kirklees Metropolitan Council           |
| Towcester Household Waste Recycling Centre              | West Northamptonshire Council           |
| Emerald Street Recycling Centre                         | Kirklees Metropolitan Council           |
| Mildenhall Household Waste Recycling Centre             | Suffolk County Council                  |
| Northampton Ecton Lane Household Waste Recycling Centre | West Northamptonshire Council           |
| Chester Household Waste Recycling Centre                | Cheshire West and Chester Council       |
| Bogleha Recycling Centre                                | Argyll and Bute Council                 |
| Bleak Hall Household Waste Recycling Centre             | Milton Keynes Council                   |
| Nab Lane Recycling Centre                               | Kirklees Metropolitan Council           |
| Household Waste Recycling Centre                        | Herefordshire County Council            |
| Hartley Wintney HWRC                                    | Hampshire County Council                |
| Brixworth Household Waste Recycling Centre              | West Northamptonshire Council           |
| Daventry Household Waste Recycling Centre               | West Northamptonshire Council           |
| Middleton-in-Teesdale HWRC                              | Durham County Council                   |
| Banchory Recycling Centre                               | Aberdeenshire council                   |
| Household Recycling Centre                              | Peterborough City Council               |
| Bucksburn Recycling Centre                              | Aberdeen City Council                   |

It's probably a good idea for us to fix these before we switch over

**Comment by DsposalTom** [comment]
I've done the first 15 - will look at doing the others at some point today

**Comment by JackGilmore** [comment]
Cheers! I'll do some work to add a list to the site grouping the HWRCs by local authority. Once that's done I'll publish what I've worked on to the staging website to make sure we're 100% happy before it goes live.

New query also includes metadata now so we can see who/when a recycling centre was last changed. For example:
```json
{
  "type": "node",
  "id": 287038358,
  "lat": 53.0105070,
  "lon": -1.7507933,
  "timestamp": "2021-03-22T14:57:50Z",
  "version": 6,
  "changeset": 101513197,
  "user": "DsposalTom",
  "uid": 11803020,
  "tags": {
    "addr:city": "Ashbourne",
    "addr:postcode": "DE6 2BJ",
    "addr:street": "Mayfield Road",
    "amenity": "recycling",
    "name": "Ashbourne household waste recycling centre",
    "opening_hours": "Mo-Su 08:30-18:00",
    "operator": "H W Martin Waste Ltd",
    "operator:type": "private",
    "owner": "Derbyshire County Council",
    "ownership": "municipal",
    "recycling:cans": "yes",
    "recycling:clothes": "yes",
    "recycling:glass": "yes",
    "recycling:paper": "yes",
    "recycling_type": "centre",
    "url": "https://www.derbyshire.gov.uk/environment/rubbish-waste/recyling-centres/centre-locations/ashbourne/ashbourne-household-waste-recycling-centre.aspx",
    "wikidata": "Q106093454"
  }
}
```

**Comment by DsposalTom** [comment]
@JackGilmore I worked through the list.  I hope there should only be one left and that is Glossop.  There was a node and a way created for that one so I'm leaving the node out.

I also picked up some extras that where called "Household Waste Recycling Centre" or "Household Recycling Centre"

Winning

**Comment by JackGilmore** [comment]
@DsposalTom I removed the node for Glossop as it appeared to be a duplicate and didn't contain any meaningful data.

New query is live on staging and is picking up 235 HWRCs: https://staging.openwastemap.uk/

Added a new report to group these by local authority: https://staging.openwastemap.uk/Reports/ByLocalAuthority

**Comment by DsposalTom** [comment]
Beautiful work Jack!!!

**Comment by JackGilmore** [comment]
Cheers! All good to go with making this live then? I can push the big red button this evening if we want 😋

**Comment by DsposalTom** [comment]
Yeah do it

**Comment by JackGilmore** [comment]
@DsposalTom New changes live: https://openwastemap.uk/
